### ISSUE TITLE
Styling the Wizard's progress bar

### ISSUE THREAD

**Issue by omryha** [madoar/angular-archwizard#117]
Hi,

Is there a way to design the step's progress bar? 
I want to change its color and width using CSS.

Thanks,

Omry

**Comment by madoar** [comment]
I'm not entirely sure what you mean by "step's progress bar"?

You can style the navigation bar via css.
An example, how this can be done, can be found at: https://github.com/madoar/angular-archwizard-demo/tree/master/src/app/custom-css and https://madoar.github.io/angular-archwizard-demo/#/custom-css

If you have any open questions feel free to add a comment.

**Comment by omryha** [comment]
Hi,

I mean how to style the progress bar line (just the default grey line, not the circles).

Thanks

**Comment by madoar** [comment]
The styling of the gray lines works analogous to the circles.
Instead of using 
```css
.custom-css aw-wizard-navigation-bar.horizontal ul.steps-indicator li.current:after {
  border-color: violet !important;
  background-color: violet !important;
}
```  

you need to use `li:before` to style the lines, i.e.:
```css
.custom-css aw-wizard-navigation-bar.horizontal ul.steps-indicator li.current:before {
  border-color: violet !important;
}
```
