### ISSUE TITLE
horizontal line in rtl horizontal wizard

### ISSUE THREAD

**Issue by benshabatnoam** [madoar/angular-archwizard#169]
Hi,

I'm using your wizard component in many of my projects and I'm loving it, nice job!.

When I'm using the wizard in a body direction RTL the horizontal line connecting the steps gets corrupted.

With this simple CSS the problem is fixed:
``` CSS
aw-wizard-navigation-bar.horizontal.large-empty-symbols ul.steps-indicator li:not(:last-child):before {
  background-color: #e6e6e6;
  content: '';
  position: absolute;
  height: 1px;
  width: calc(100% - 50px);
  top: -25px;
  right: calc(50% + 25px);
}
```

It is a bit of annoying to have to copy this CSS to each one of my projects.

Is it possible to get it inside of one of your next versions?

Thanks

**Comment by madoar** [comment]
Can you please add a screenshot, showing the problem, to help me understand how it looks?

In addition:
In the develop branch, the stylesheets of the navigation bar have been restructured.
Can you please try building the develop branch and test, whether the changes fix the issue?

**Comment by benshabatnoam** [comment]
This is how it looks like:
![image](https://user-images.githubusercontent.com/5260028/48194123-cfed6600-e354-11e8-8df4-8ba0fc2f5b29.png)

Sure, I'll try it with the develop branch. I'll update soon.
Thanks

**Comment by benshabatnoam** [comment]
This is the CSS needed:

``` CSS
aw-wizard-navigation-bar.horizontal.small ul.steps-indicator li:not(:first-child):before {
  background-color:#e6e6e6;
  content:'';
  position:absolute;
  height:1px;
  width:calc(100% - 14px);
  top:-7px;
  left:calc(50% + 14px / 2)
}

aw-wizard-navigation-bar.horizontal.small ul.steps-indicator li:first-child:before {
  display: none;
}

aw-wizard-navigation-bar.horizontal.large-filled ul.steps-indicator li:not(:first-child):before,
aw-wizard-navigation-bar.horizontal.large-empty ul.steps-indicator li:not(:first-child):before,
aw-wizard-navigation-bar.horizontal.large-filled-symbols ul.steps-indicator li:not(:first-child):before,
aw-wizard-navigation-bar.horizontal.large-empty-symbols ul.steps-indicator li:not(:first-child):before {
  background-color:#e6e6e6;
  content:'';
  position:absolute;
  height:1px;
  width:calc(100% - 50px);
  top:-25px;
  left:calc(50% + 50px / 2)
}

aw-wizard-navigation-bar.horizontal.large-filled ul.steps-indicator li:first-child:before,
aw-wizard-navigation-bar.horizontal.large-empty ul.steps-indicator li:first-child:before,
aw-wizard-navigation-bar.horizontal.large-filled-symbols ul.steps-indicator li:first-child:before,
aw-wizard-navigation-bar.horizontal.large-empty-symbols ul.steps-indicator li:first-child:before {
  display: none;
}
```

See screenshot without this CSS:
![image](https://user-images.githubusercontent.com/5260028/48363910-c004b780-e6af-11e8-9e27-7957bb2522e5.png)

See screenshot with this CSS:
![image](https://user-images.githubusercontent.com/5260028/48363979-dd398600-e6af-11e8-9e5e-bab3afbea5b1.png)
