### ISSUE TITLE
navBarDirection "right-to-left" not working correctly

### ISSUE THREAD

**Issue by omardoma** [madoar/angular-archwizard#280]
<img width="1039" alt="Screen Shot 2020-03-18 at 2 10 25 PM" src="https://user-images.githubusercontent.com/25301162/76959519-64d97980-6922-11ea-9dcc-79e7f1d59701.png">

Browser: Chrome v80.0.3987.132
OS: MacOS Catalina
Version: 5.0.0
Angular Version: 8.2.14

Usage:

```html
        <aw-wizard #wizard navBarLayout="large-filled-symbols" [disableNavigationBar]="true"
          [navBarDirection]="'right-to-left'">
          <aw-wizard-step [stepTitle]="t('step1.label')" [navigationSymbol]="{ symbol: t('step1.symbol') }">
          </aw-wizard-step>
          <aw-wizard-step [stepTitle]="t('step2.label')" [navigationSymbol]="{ symbol: t('step2.symbol') }">
          </aw-wizard-step>
          <aw-wizard-step [stepTitle]="t('step3.label')" [navigationSymbol]="{ symbol: t('step3.symbol') }">
          </aw-wizard-step>
        </aw-wizard>
```

**Comment by omardoma** [comment]
Also I can't upgrade to Angular 9 yet due to other libs dependencies that still haven't upgraded, so hopefully a fix can be published to the v5.0.0 as well

**Comment by omardoma** [comment]
Also I have checked the issues and this one #169 seems to be related

**Comment by omardoma** [comment]
I think I figured out the bug, so in RTL apps, the html element `dir` is set to `rtl` as well as the body has a css property `direction: rtl`, this alone with no navBarDirection set on the wizard makes the steps have the correct direction, as it adapts to the document's direction, but only the horizontal line css needs fixing.

With rtl mode and no navBarDirection set, the steps direction is correct but the horizontal line css needs to be fixed:

<img width="1039" alt="Screen Shot 2020-03-18 at 2 37 10 PM" src="https://user-images.githubusercontent.com/25301162/76961506-20e87380-6926-11ea-92eb-ad6880c4f297.png">

As a workaround I have used the css mentioned in issue #169 to fix it:

```css
.rtl {
  // Workaround this issue: https://github.com/madoar/angular-archwizard/issues/169
  aw-wizard-navigation-bar.horizontal.small
    ul.steps-indicator
    li:not(:first-child):before {
    background-color: #e6e6e6;
    content: '';
    position: absolute;
    height: 1px;
    width: calc(100% - 14px);
    top: -7px;
    left: calc(50% + 14px / 2);
  }

  aw-wizard-navigation-bar.horizontal.small
    ul.steps-indicator
    li:first-child:before {
    display: none;
  }

  aw-wizard-navigation-bar.horizontal.large-filled
    ul.steps-indicator
    li:not(:first-child):before,
  aw-wizard-navigation-bar.horizontal.large-empty
    ul.steps-indicator
    li:not(:first-child):before,
  aw-wizard-navigation-bar.horizontal.large-filled-symbols
    ul.steps-indicator
    li:not(:first-child):before,
  aw-wizard-navigation-bar.horizontal.large-empty-symbols
    ul.steps-indicator
    li:not(:first-child):before {
    background-color: #e6e6e6;
    content: '';
    position: absolute;
    height: 1px;
    width: calc(100% - 50px);
    top: -25px;
    left: calc(50% + 50px / 2);
  }

  aw-wizard-navigation-bar.horizontal.large-filled
    ul.steps-indicator
    li:first-child:before,
  aw-wizard-navigation-bar.horizontal.large-empty
    ul.steps-indicator
    li:first-child:before,
  aw-wizard-navigation-bar.horizontal.large-filled-symbols
    ul.steps-indicator
    li:first-child:before,
  aw-wizard-navigation-bar.horizontal.large-empty-symbols
    ul.steps-indicator
    li:first-child:before {
    display: none;
  }
}
```
